In [36]:
import pandas as pd
import numpy as np
import glob
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

In [37]:
# Load the data

# Get all CSV files from processed folder
csv_files = glob.glob('../data/processed/*.csv')  

dfs = []

# Read each CSV file and append to the list
for file in sorted(csv_files): 
    df = pd.read_csv(file)
    dfs.append(df)

# Concatenate all dataframes
tennis_df = pd.concat(dfs, ignore_index=True)

tennis_df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,AvgW,AvgL
0,2013-339,Brisbane,Hard,28,A,20121230,1,105357,NaN,Q,...,8.0,8.0,3.0,7.0,199.0,239.0,79.0,655.0,1.71,2.08
1,2013-339,Brisbane,Hard,28,A,20121230,2,103720,NaN,WC,...,19.0,14.0,6.0,10.0,83.0,625.0,162.0,339.0,1.22,4.07
2,2013-339,Brisbane,Hard,28,A,20121230,3,104797,NaN,NaN,...,9.0,7.0,9.0,13.0,43.0,897.0,30.0,1175.0,1.88,1.85
3,2013-339,Brisbane,Hard,28,A,20121230,4,103813,NaN,NaN,...,7.0,12.0,1.0,6.0,41.0,927.0,35.0,1075.0,1.73,2.05
4,2013-339,Brisbane,Hard,28,A,20121230,5,103990,NaN,NaN,...,20.0,11.0,0.0,1.0,114.0,495.0,69.0,710.0,2.66,1.47

In [38]:
tennis_df.shape

(33517, 51)

In [39]:
tennis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33517 entries, 0 to 33516
Data columns (total 51 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          33517 non-null  object
 1   tourney_name        33517 non-null  object
 2   surface             33464 non-null  object
 3   draw_size           33517 non-null  int64
 4   tourney_level       33517 non-null  object
 5   tourney_date        33517 non-null  int64
 6   match_num           33517 non-null  int64
 7   winner_id           33517 non-null  int64
 8   winner_seed         14246 non-null  float64
 9   winner_entry        4621 non-null   object
 10  winner_name         33517 non-null  object
 11  winner_hand         33517 non-null  object
 12  winner_ht           33226 non-null  float64
 13  winner_ioc          33517 non-null  object
 14  winner_age          33514 non-null  float64
 15  loser_id            33517 non-null  int64
 16  loser_seed          8189 non-null   float64
 17  loser_entry         7357 non-null   object
 18  loser_name          33517 non-null  object
 19  loser_hand          33513 non-null  object
 20  loser_ht            32813 non-null  float64
 21  loser_ioc           33517 non-null  object
 22  loser_age           33514 non-null  float64
 23  score               33517 non-null  object
 24  best_of             33517 non-null  int64
 25  round               33517 non-null  object
 26  minutes             30135 non-null  float64
 27  w_ace               31776 non-null  float64
 28  w_df                31776 non-null  float64
 29  w_svpt              31776 non-null  float64
 30  w_1stIn             31776 non-null  float64
 31  w_1stWon            31776 non-null  float64
 32  w_2ndWon            31776 non-null  float64
 33  w_SvGms             31776 non-null  float64
 34  w_bpSaved           31776 non-null  float64
 35  w_bpFaced           31776 non-null  float64
 36  l_ace               31776 non-null  float64
 37  l_df                31776 non-null  float64
 38  l_svpt              31776 non-null  float64
 39  l_1stIn             31776 non-null  float64
 40  l_1stWon            31776 non-null  float64
 41  l_2ndWon            31776 non-null  float64
 42  l_SvGms             31776 non-null  float64
 43  l_bpSaved           31776 non-null  float64
 44  l_bpFaced           31776 non-null  float64
 45  winner_rank         33330 non-null  float64
 46  winner_rank_points  33330 non-null  float64
 47  loser_rank          33039 non-null  float64
 48  loser_rank_points   33039 non-null  float64
 49  AvgW                28112 non-null  float64
 50  AvgL                28112 non-null  float64
dtypes: float64(31), int64(6), object(14)
memory usage: 13.0+ MB

In [40]:
tennis_df.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points',
       'AvgW', 'AvgL'],
      dtype='object')

In [41]:
# Preprocessing
tennis_df.drop(columns=['tourney_id', 'tourney_name', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_ioc', 'loser_id', 'loser_seed', 'loser_entry', 
       'loser_name', 'loser_ioc', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced'], inplace=True)

print(f"Remaining columns: {tennis_df.columns}")

Remaining columns: Index(['surface', 'winner_hand', 'winner_ht', 'winner_age', 'loser_hand',
       'loser_ht', 'loser_age', 'winner_rank', 'winner_rank_points',
       'loser_rank', 'loser_rank_points', 'AvgW', 'AvgL'],
      dtype='object')

In [42]:
# Remove missing values
tennis_df = tennis_df.dropna()
tennis_df.shape

(27982, 13)

In [43]:
# Encode surface
surface_dummies = pd.get_dummies(tennis_df['surface'], prefix='surface')
tennis_df = pd.concat([tennis_df.drop(columns=['surface']), surface_dummies], axis=1)

# Encode winner and loser hand
tennis_df['winner_hand'] = tennis_df['winner_hand'].map({'L': 0, 'R': 1})
tennis_df['loser_hand'] = tennis_df['loser_hand'].map({'L': 0, 'R': 1})

tennis_df.head()

,winner_hand,winner_ht,winner_age,loser_hand,loser_ht,loser_age,winner_rank,winner_rank_points,loser_rank,loser_rank_points,AvgW,AvgL,surface_Clay,surface_Grass,surface_Hard
0,1.0,183.0,23.5,1.0,180.0,24.6,199.0,239.0,79.0,655.0,1.71,2.08,False,False,True
1,1.0,180.0,31.8,1.0,180.0,31.2,83.0,625.0,162.0,339.0,1.22,4.07,False,False,True
2,1.0,185.0,26.3,0.0,191.0,23.4,43.0,897.0,30.0,1175.0,1.88,1.85,False,False,True
3,0.0,185.0,31.4,1.0,185.0,31.0,41.0,927.0,35.0,1075.0,1.73,2.05,False,False,True
4,1.0,180.0,30.6,1.0,185.0,20.6,114.0,495.0,69.0,710.0,2.66,1.47,False,False,True

Because we only have winner and losers instead of player vs player, we need to randomly flip rows to represent that scenario so the winner isn't always player one.

In [44]:
# Create new columns for player1 and player2
# First, create a random mask to determine which rows to flip
np.random.seed(42)  # for reproducibility
flip_mask = np.random.rand(len(tennis_df)) < 0.5

# Initialize new columns
tennis_df['P1Hand'] = np.where(flip_mask, tennis_df['loser_hand'], tennis_df['winner_hand'])
tennis_df['P2Hand'] = np.where(flip_mask, tennis_df['winner_hand'], tennis_df['loser_hand'])

tennis_df['P1Ht'] = np.where(flip_mask, tennis_df['loser_ht'], tennis_df['winner_ht'])
tennis_df['P2Ht'] = np.where(flip_mask, tennis_df['winner_ht'], tennis_df['loser_ht'])

tennis_df['P1Age'] = np.where(flip_mask, tennis_df['loser_age'], tennis_df['winner_age'])
tennis_df['P2Age'] = np.where(flip_mask, tennis_df['winner_age'], tennis_df['loser_age'])

tennis_df['P1Rank'] = np.where(flip_mask, tennis_df['loser_rank'], tennis_df['winner_rank'])
tennis_df['P2Rank'] = np.where(flip_mask, tennis_df['winner_rank'], tennis_df['loser_rank'])

tennis_df['P1Pts'] = np.where(flip_mask, tennis_df['loser_rank_points'], tennis_df['winner_rank_points'])
tennis_df['P2Pts'] = np.where(flip_mask, tennis_df['winner_rank_points'], tennis_df['loser_rank_points'])

tennis_df['P1Odds'] = np.where(flip_mask, tennis_df['AvgL'], tennis_df['AvgW'])
tennis_df['P2Odds'] = np.where(flip_mask, tennis_df['AvgW'], tennis_df['AvgL'])

# Add label (0 if player1 wins, 1 if player2 wins)
tennis_df['label'] = flip_mask.astype(int)

# Drop the original columns as they're no longer needed
tennis_df = tennis_df.drop(columns=['winner_hand', 'loser_hand', 'winner_ht', 'loser_ht', 'winner_age', 'loser_age', 'winner_rank', 'loser_rank', 'winner_rank_points', 'loser_rank_points', 'AvgL', 'AvgW'])

tennis_df.head()

,surface_Clay,surface_Grass,surface_Hard,P1Hand,P2Hand,P1Ht,P2Ht,P1Age,P2Age,P1Rank,P2Rank,P1Pts,P2Pts,P1Odds,P2Odds,label
0,False,False,True,1.0,1.0,180.0,183.0,24.6,23.5,79.0,199.0,655.0,239.0,2.08,1.71,1
1,False,False,True,1.0,1.0,180.0,180.0,31.8,31.2,83.0,162.0,625.0,339.0,1.22,4.07,0
2,False,False,True,1.0,0.0,185.0,191.0,26.3,23.4,43.0,30.0,897.0,1175.0,1.88,1.85,0
3,False,False,True,0.0,1.0,185.0,185.0,31.4,31.0,41.0,35.0,927.0,1075.0,1.73,2.05,0
4,False,False,True,1.0,1.0,185.0,180.0,20.6,30.6,69.0,114.0,710.0,495.0,1.47,2.66,1

In [45]:
# Train test split
X = tennis_df.drop(columns=['label'])
y = tennis_df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
# Primary model
# Define the parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 6, 10],
    'learning_rate': [0.01, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 3]
}

# Create GridSearchCV object
grid_search = GridSearchCV(
    estimator=XGBClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=2
)

# Fit the grid search
grid_search.fit(X_train, y_train)

# Print the best parameters and score
print(f"\nBest parameters: {grid_search.best_params_}")
print(f"Best cross-validation score: {grid_search.best_score_:.4f}")

# Get the best model
best_model = grid_search.best_estimator_

# Predict
y_pred = best_model.predict(X_test)

# Evaluate
print(classification_report(y_test, y_pred))
print('XGBoost Accuracy: ', accuracy_score(y_test, y_pred))

# Save the model
joblib.dump(best_model, '../models/primary_model.joblib')

Fitting 5 folds for each of 144 candidates, totalling 720 fits

Best parameters: {'colsample_bytree': 1.0, 'learning_rate': 0.01, 'max_depth': 3, 'min_child_weight': 1, 'n_estimators': 100, 'subsample': 1.0}
Best cross-validation score: 0.6921
              precision    recall  f1-score   support

           0       0.69      0.68      0.68      2798
           1       0.68      0.69      0.69      2799

    accuracy                           0.69      5597
   macro avg       0.69      0.69      0.68      5597
weighted avg       0.69      0.69      0.68      5597

XGBoost Accuracy:  0.6850098266928711

['../models/primary_model.joblib']

In [47]:
# Secondary model (only odds, rank, points, and surface)
X = tennis_df.drop(columns=['label','P1Hand','P2Hand','P1Ht','P2Ht','P1Age','P2Age'])
y = tennis_df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 6, 10],
    'learning_rate': [0.01, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 3]
}

# Create GridSearchCV object
grid_search = GridSearchCV(
    estimator=XGBClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=2
)

# Fit the grid search
grid_search.fit(X_train, y_train)

# Print the best parameters and score
print(f"\nBest parameters: {grid_search.best_params_}")
print(f"Best cross-validation score: {grid_search.best_score_:.4f}")

# Get the best model
best_model = grid_search.best_estimator_

# Predict
y_pred = best_model.predict(X_test)

# Evaluate
print(classification_report(y_test, y_pred))
print('XGBoost Accuracy: ', accuracy_score(y_test, y_pred))

# Save the model
joblib.dump(best_model, '../models/secondary_model.joblib')

Fitting 5 folds for each of 144 candidates, totalling 720 fits

Best parameters: {'colsample_bytree': 1.0, 'learning_rate': 0.01, 'max_depth': 3, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 0.8}
Best cross-validation score: 0.6922
              precision    recall  f1-score   support

           0       0.69      0.68      0.68      2798
           1       0.68      0.69      0.69      2799

    accuracy                           0.69      5597
   macro avg       0.69      0.69      0.69      5597
weighted avg       0.69      0.69      0.69      5597

XGBoost Accuracy:  0.6851884938359836

['../models/secondary_model.joblib']

In [48]:
# Tertiary model (only odds and surface)
X = tennis_df.drop(columns=['label','P1Hand','P2Hand','P1Ht','P2Ht','P1Age','P2Age','P1Rank','P2Rank','P1Pts','P2Pts'])
y = tennis_df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 6, 10],
    'learning_rate': [0.01, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'min_child_weight': [1, 3]
}

# Create GridSearchCV object
grid_search = GridSearchCV(
    estimator=XGBClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=2
)

# Fit the grid search
grid_search.fit(X_train, y_train)

# Print the best parameters and score
print(f"\nBest parameters: {grid_search.best_params_}")
print(f"Best cross-validation score: {grid_search.best_score_:.4f}")

# Get the best model
best_model = grid_search.best_estimator_

# Predict
y_pred = best_model.predict(X_test)

# Evaluate
print(classification_report(y_test, y_pred))
print('XGBoost Accuracy: ', accuracy_score(y_test, y_pred))

# Save the model
joblib.dump(best_model, '../models/tertiary_model.joblib')

Fitting 5 folds for each of 144 candidates, totalling 720 fits

Best parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 200, 'subsample': 1.0}
Best cross-validation score: 0.6942
              precision    recall  f1-score   support

           0       0.70      0.64      0.67      2798
           1       0.67      0.72      0.69      2799

    accuracy                           0.68      5597
   macro avg       0.68      0.68      0.68      5597
weighted avg       0.68      0.68      0.68      5597

XGBoost Accuracy:  0.6801858138288369

['../models/tertiary_model.joblib']